### ISSUE TITLE
Why is KNN's confidence usually 1?

### ISSUE THREAD

**Issue by DiTo97** [RubixML/Divorce#3]
I have experimented quite a bit with this example over the past few days as an initial approach towards learning Rubix, and I have noticed that the confidence with which the KNN formulates its predictions is always 1 for the up class, and never in-between.

I would expect situations where the dominant class is not so clear, as the K neighbors may very well be mixed between the two.

I have also looked at the source code for the _probaSample_ function and it looks correct to me. Have you experienced this result in your testing with the _Divorce_ predictor? Could it be because of the nature of the problem, i.e.,  could the 54-dimensional feature vectors reside within well-defined boundaries for each of the two classes, _married_ and _divorced_?

**Comment by andrewdalpino** [comment]
Hi @DiTo97 thanks for the question! Yes, I have noticed this pattern in my own experiments. Take a look at the following plots of various embeddings of the Divorce dataset. You'll notice that, in these latent spaces, the clusters are usually pretty well defined and linearly separable. This tells me that the data in high dimensions is probably also fairly discernable. So it's not unusual for KNN to report a fully confident (probable) prediction, especially with a low *k* setting. You could try increasing this value if you prefer to spread the probability over more neighbors.

![Divorce Dataset LDA Embedding](https://user-images.githubusercontent.com/18690561/121297938-b1f39380-c8b8-11eb-96b9-944f362e223f.png)
![Divorce Dataset t-SNE Embedding](https://user-images.githubusercontent.com/18690561/121297939-b1f39380-c8b8-11eb-975a-d97ce9848977.png)
![Divorce Dataset Truncated SVD Embedding](https://user-images.githubusercontent.com/18690561/121297941-b1f39380-c8b8-11eb-8d29-c31686817409.png)
![Divorce Dataset PCA Embedding ](https://user-images.githubusercontent.com/18690561/121297943-b1f39380-c8b8-11eb-9887-eb67e343e5d0.png)
